# ========================================================
# 🗄️ DATABASE - USER MANAGEMENT (UPDATED)
# ========================================================

import sqlite3
from config import DB_NAME

def get_connection():
    return sqlite3.connect(DB_NAME, check_same_thread=False)

def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    # ----------------------------------------------------
    # TABLES SETUP
    # ----------------------------------------------------
    # Total users (Ever joined)
    cursor.execute("CREATE TABLE IF NOT EXISTS users (user_id INTEGER PRIMARY KEY)")
    
    # User status (Live/Dead for Broadcasts)
    cursor.execute("CREATE TABLE IF NOT EXISTS user_status (user_id INTEGER PRIMARY KEY, is_live INTEGER DEFAULT 1)")
    
    cursor.execute("CREATE TABLE IF NOT EXISTS stats (key TEXT PRIMARY KEY, value INTEGER)")
    cursor.execute("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT)")
    cursor.execute("CREATE TABLE IF NOT EXISTS buttons (btn_id INTEGER PRIMARY KEY, text TEXT, price INTEGER)")
    cursor.execute("CREATE TABLE IF NOT EXISTS menu_buttons (btn_id INTEGER PRIMARY KEY, text TEXT, link TEXT)")
    cursor.execute("""CREATE TABLE IF NOT EXISTS admin_users (
        user_id INTEGER PRIMARY KEY,
        added_at TEXT DEFAULT CURRENT_TIMESTAMP
    )""")

    # Premium/access control for NEW ADMIN accounts.
    cursor.execute("""CREATE TABLE IF NOT EXISTS admin_access (
        user_id INTEGER PRIMARY KEY,
        plan TEXT NOT NULL DEFAULT 'FREE',
        activated_at TEXT,
        expires_at TEXT,
        user_limit INTEGER NOT NULL DEFAULT 500,
        revenue_limit INTEGER NOT NULL DEFAULT 150,
        status TEXT NOT NULL DEFAULT 'ACTIVE',
        notified TEXT NOT NULL DEFAULT ''
    )""")

    # One-time premium activation keys generated by the Permanent Admin.
    cursor.execute("""CREATE TABLE IF NOT EXISTS premium_keys (
        key_id INTEGER PRIMARY KEY AUTOINCREMENT,
        key_hash TEXT UNIQUE NOT NULL,
        key_hint TEXT NOT NULL,
        plan TEXT NOT NULL,
        created_by INTEGER NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        used_by INTEGER,
        used_at TEXT,
        status TEXT NOT NULL DEFAULT 'UNUSED'
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS admin_access_events (
        event_id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        event_type TEXT NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS payment_records (
        payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        button_id INTEGER NOT NULL,
        amount INTEGER NOT NULL,
        screenshot_file_id TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        approved_by INTEGER,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        approved_at TEXT,
        payment_type TEXT NOT NULL DEFAULT 'user'
    )""")
    try:
        cursor.execute("ALTER TABLE payment_records ADD COLUMN payment_type TEXT NOT NULL DEFAULT 'user'")
    except sqlite3.OperationalError:
        pass
    cursor.execute("""CREATE TABLE IF NOT EXISTS admin_log_channels (
        user_id INTEGER PRIMARY KEY,
        channel TEXT NOT NULL,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS admin_upis (
        user_id INTEGER PRIMARY KEY,
        upi_id TEXT NOT NULL,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )""")
    # Custom premium-key fields are additive for old databases.
    for ddl in (
        "ALTER TABLE premium_keys ADD COLUMN custom_user_limit INTEGER",
        "ALTER TABLE premium_keys ADD COLUMN custom_revenue_limit INTEGER",
        "ALTER TABLE premium_keys ADD COLUMN custom_days INTEGER",
    ):
        try:
            cursor.execute(ddl)
        except sqlite3.OperationalError:
            pass
    
    try:
        cursor.execute("ALTER TABLE menu_buttons ADD COLUMN link TEXT")
    except sqlite3.OperationalError:
        pass

    conn.commit()

    # ----------------------------------------------------
    # DEFAULT DATA SEEDING
    # ----------------------------------------------------
    cursor.execute("INSERT OR IGNORE INTO stats (key, value) VALUES ('payments', 0)")
    cursor.execute("INSERT OR IGNORE INTO stats (key, value) VALUES ('total_amount', 0)")
    cursor.execute("INSERT OR IGNORE INTO settings (key, value) VALUES ('upi_id', 'your_upi@ybl')")
    cursor.execute("INSERT OR IGNORE INTO settings (key, value) VALUES ('demo_link', 'https://t.me/your_demo_channel')")
    cursor.execute("INSERT OR IGNORE INTO settings (key, value) VALUES ('contact_link', 'https://t.me/your_contact_link')")
    cursor.execute("INSERT OR IGNORE INTO settings (key, value) VALUES ('permanent_upi_id', '')")

    # V9 requested premium pricing for New Admin purchases.
    for bid, label, price in (
        (1, 'PREMIUM LITE', 199),
        (2, 'PREMIUM XD', 299),
        (3, 'PREMIUM PRO', 399),
    ):
        cursor.execute("INSERT OR REPLACE INTO buttons (btn_id, text, price) VALUES (?, ?, ?)", (bid, label, price))

    cursor.execute("INSERT OR IGNORE INTO menu_buttons (btn_id, text, link) VALUES (1, 'PREMIUM', '')")
    cursor.execute("INSERT OR IGNORE INTO menu_buttons (btn_id, text, link) VALUES (2, 'DEMO', '')")
    cursor.execute("INSERT OR IGNORE INTO menu_buttons (btn_id, text, link) VALUES (3, 'CONTACT', '')")
    
    conn.commit()
    conn.close()

# ========================================================
# 👤 USER MANAGEMENT (TOTAL & LIVE)
# ========================================================

def add_user(user_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT OR IGNORE INTO users (user_id) VALUES (?)", (user_id,))
    cursor.execute("INSERT OR IGNORE INTO user_status (user_id, is_live) VALUES (?, 1)", (user_id,))
    conn.commit()
    conn.close()

def add_users_bulk(user_ids: list) -> int:
    if not user_ids:
        return 0
    conn = get_connection()
    cursor = conn.cursor()
    
    data = [(int(uid),) for uid in user_ids]
    cursor.executemany("INSERT OR IGNORE INTO users (user_id) VALUES (?)", data)
    
    status_data = [(int(uid), 1) for uid in user_ids]
    cursor.executemany("INSERT OR IGNORE INTO user_status (user_id, is_live) VALUES (?, ?)", status_data)
    
    conn.commit()
    conn.close()
    return len(data)

def mark_user_live(user_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO user_status (user_id, is_live) 
        VALUES (?, 1) ON CONFLICT(user_id) DO UPDATE SET is_live = 1
    """, (int(user_id),))
    conn.commit()
    conn.close()

def mark_user_dead(user_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO user_status (user_id, is_live) 
        VALUES (?, 0) ON CONFLICT(user_id) DO UPDATE SET is_live = 0
    """, (int(user_id),))
    conn.commit()
    conn.close()

# Alias so handlers.py broadcast doesn't crash when deleting dead users
def remove_user(user_id: int):
    mark_user_dead(user_id)

def get_live_users() -> list:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT u.user_id FROM users u
        LEFT JOIN user_status s ON u.user_id = s.user_id
        WHERE s.is_live = 1 OR s.user_id IS NULL
    """)
    users = [row[0] for row in cursor.fetchall()]
    conn.close()
    return users

def get_all_users() -> list:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT user_id FROM users")
    users = [row[0] for row in cursor.fetchall()]
    conn.close()
    return users

def get_total_users_count() -> int:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM users")
    count = cursor.fetchone()[0]
    conn.close()
    return count

def get_live_users_count() -> int:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT COUNT(*) FROM users u
        LEFT JOIN user_status s ON u.user_id = s.user_id
        WHERE s.is_live = 1 OR s.user_id IS NULL
    """)
    count = cursor.fetchone()[0]
    conn.close()
    return count

# ========================================================
# ⚙️ SETTINGS & STATS
# ========================================================

def get_setting(key: str) -> str:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT value FROM settings WHERE key = ?", (key,))
    res = cursor.fetchone()
    conn.close()
    return res[0] if res else ""

def update_setting(key: str, value: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)", (key, str(value)))
    conn.commit()
    conn.close()

def get_stat(key: str) -> int:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT value FROM stats WHERE key = ?", (key,))
    res = cursor.fetchone()
    conn.close()
    return res[0] if res else 0

def increment_stat(key: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("UPDATE stats SET value = value + 1 WHERE key = ?", (key,))
    conn.commit()
    conn.close()

# ========================================================
# 🔘 MENUS & BUTTONS
# ========================================================

def get_menu_buttons() -> dict:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT btn_id, text, link FROM menu_buttons ORDER BY btn_id ASC")
    rows = cursor.fetchall()
    conn.close()
    return {row[0]: (row[1], row[2] if len(row) > 2 and row[2] else "") for row in rows}

def update_menu_button(btn_id: int, text: str, link: str = ""):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT OR REPLACE INTO menu_buttons (btn_id, text, link) VALUES (?, ?, ?)", (btn_id, text.upper(), link))
    conn.commit()
    conn.close()

def set_menu_button_link(btn_id: int, link: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("UPDATE menu_buttons SET link = ? WHERE btn_id = ?", (link, btn_id))
    conn.commit()
    conn.close()

def delete_menu_button(btn_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM menu_buttons WHERE btn_id = ?", (btn_id,))
    conn.commit()
    conn.close()

def get_premium_buttons() -> list:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT btn_id, text, price FROM buttons ORDER BY btn_id ASC")
    btns = cursor.fetchall()
    conn.close()
    return btns

def get_button_by_id(btn_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT text, price FROM buttons WHERE btn_id = ?", (btn_id,))
    res = cursor.fetchone()
    conn.close()
    return res

def set_button_data(btn_id: int, text: str, price: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT OR REPLACE INTO buttons (btn_id, text, price) VALUES (?, ?, ?)", (btn_id, text, price))
    conn.commit()
    conn.close()


# ========================================================
# 💳 PAYMENT RECORDS
# ========================================================

def create_payment(user_id: int, button_id: int, amount: int, screenshot_file_id: str = "", payment_type: str = "user") -> int:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO payment_records (user_id, button_id, amount, screenshot_file_id, payment_type) VALUES (?, ?, ?, ?, ?)",
        (int(user_id), int(button_id), int(amount), screenshot_file_id, str(payment_type)),
    )
    payment_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return int(payment_id)


def get_payment(payment_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT payment_id, user_id, button_id, amount, screenshot_file_id, status, approved_by, created_at, approved_at, payment_type FROM payment_records WHERE payment_id = ?", (int(payment_id),))
    row = cursor.fetchone()
    conn.close()
    return row


def approve_payment(payment_id: int, admin_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT user_id, button_id, amount, status FROM payment_records WHERE payment_id = ?", (int(payment_id),))
    row = cursor.fetchone()
    if not row:
        conn.close()
        return None, False
    user_id, button_id, amount, status = row
    if status != 'pending':
        conn.close()
        return row, False
    cursor.execute("UPDATE payment_records SET status='approved', approved_by=?, approved_at=CURRENT_TIMESTAMP WHERE payment_id=? AND status='pending'", (int(admin_id), int(payment_id)))
    if cursor.rowcount != 1:
        conn.rollback()
        conn.close()
        return row, False
    cursor.execute("UPDATE stats SET value=value+1 WHERE key='payments'")
    cursor.execute("UPDATE stats SET value=value+? WHERE key='total_amount'", (int(amount),))
    conn.commit()
    conn.close()
    return (user_id, button_id, amount, 'approved'), True


def reject_payment(payment_id: int):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT user_id, button_id, amount, status FROM payment_records WHERE payment_id = ?", (int(payment_id),))
    row = cursor.fetchone()
    if not row:
        conn.close()
        return None, False
    if row[3] != 'pending':
        conn.close()
        return row, False
    cursor.execute("UPDATE payment_records SET status='rejected' WHERE payment_id=? AND status='pending'", (int(payment_id),))
    changed = cursor.rowcount == 1
    conn.commit()
    conn.close()
    return row, changed


# ========================================================
# 👑 DATABASE-MANAGED ADMIN SYSTEM
# ========================================================

def get_new_admins() -> list:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT user_id, added_at FROM admin_users ORDER BY rowid ASC")
    rows = cursor.fetchall()
    conn.close()
    return rows

def config_permanent_admin() -> int:
    from config import PERMANENT_ADMIN
    return int(PERMANENT_ADMIN)

def get_admin_ids() -> list:
    ids = [config_permanent_admin()]
    for user_id, _ in get_new_admins():
        if int(user_id) not in ids:
            ids.append(int(user_id))
    return ids

def add_new_admin(user_id: int) -> tuple:
    user_id = int(user_id)
    if user_id == config_permanent_admin():
        return False, "permanent"
    conn = get_connection(); cursor = conn.cursor()
    cursor.execute("SELECT 1 FROM admin_users WHERE user_id = ?", (user_id,))
    if cursor.fetchone():
        conn.close(); return False, "exists"
    cursor.execute("INSERT INTO admin_users (user_id) VALUES (?)", (user_id,))
    # Every new admin starts on the FREE tier; Permanent Admin remains unrestricted.
    _set_access_for_conn(cursor, user_id, "FREE")
    conn.commit()
    cursor.execute("SELECT COUNT(*) FROM admin_users")
    count = cursor.fetchone()[0]
    conn.close()
    return True, ("owner" if count == 1 else "added")

def remove_new_admin(user_id: int) -> tuple:
    user_id = int(user_id)
    if user_id == config_permanent_admin():
        return False, "permanent"
    conn = get_connection(); cursor = conn.cursor()
    cursor.execute("SELECT 1 FROM admin_users WHERE user_id = ?", (user_id,))
    if not cursor.fetchone():
        conn.close(); return False, "not_found"
    cursor.execute("DELETE FROM admin_users WHERE user_id = ?", (user_id,))
    cursor.execute("DELETE FROM admin_access WHERE user_id = ?", (user_id,))
    conn.commit(); conn.close()
    return True, "removed"


# ========================================================
# 👑 NEW ADMIN PREMIUM / ACCESS CONTROL
# ========================================================

PREMIUM_PLANS = {
    "FREE": {"user_limit": 500, "revenue_limit": 150, "days": 2, "price": 0},
    "PREMIUM_LITE": {"user_limit": 2000, "revenue_limit": 800, "days": 7, "price": 199},
    "PREMIUM_XD": {"user_limit": 4000, "revenue_limit": 1500, "days": 14, "price": 299},
    "PREMIUM_PRO": {"user_limit": 10000, "revenue_limit": 5000, "days": 30, "price": 399},
}

def _plan_row(plan: str):
    return PREMIUM_PLANS.get(str(plan).upper(), PREMIUM_PLANS["FREE"])

def _set_access_for_conn(cursor, user_id: int, plan: str, activated_at=None):
    plan = str(plan).upper()
    p = _plan_row(plan)
    import datetime
    now = datetime.datetime.utcnow()
    activated = activated_at or now.strftime("%Y-%m-%d %H:%M:%S")
    expires = None
    if p["days"] is not None:
        expires = (now + datetime.timedelta(days=p["days"])).strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute("""
        INSERT INTO admin_access
        (user_id, plan, activated_at, expires_at, user_limit, revenue_limit, status, notified)
        VALUES (?, ?, ?, ?, ?, ?, 'ACTIVE', '')
        ON CONFLICT(user_id) DO UPDATE SET
            plan=excluded.plan,
            activated_at=excluded.activated_at,
            expires_at=excluded.expires_at,
            user_limit=excluded.user_limit,
            revenue_limit=excluded.revenue_limit,
            status='ACTIVE',
            notified=''
    """, (
        int(user_id), plan, activated, expires,
        -1 if p["user_limit"] is None else int(p["user_limit"]),
        -1 if p["revenue_limit"] is None else int(p["revenue_limit"]),
    ))

def ensure_admin_access_record(user_id: int):
    user_id = int(user_id)
    if user_id == config_permanent_admin():
        return
    conn=get_connection(); cur=conn.cursor()
    cur.execute("SELECT 1 FROM admin_users WHERE user_id=?", (user_id,))
    if cur.fetchone():
        cur.execute("SELECT 1 FROM admin_access WHERE user_id=?", (user_id,))
        if not cur.fetchone():
            cur.execute("SELECT added_at FROM admin_users WHERE user_id=?", (user_id,))
            added=cur.fetchone()
            _set_access_for_conn(cur, user_id, "FREE", added[0] if added else None)
    conn.commit(); conn.close()

def get_admin_access(user_id: int):
    user_id=int(user_id)
    if user_id == config_permanent_admin():
        return {
            "user_id": user_id, "plan": "PERMANENT", "status": "ACTIVE",
            "user_limit": None, "revenue_limit": None, "expires_at": None,
            "activated_at": None, "unrestricted": True, "users": get_total_users_count(),
            "revenue": get_stat("total_amount"),
        }
    ensure_admin_access_record(user_id)
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""SELECT user_id, plan, activated_at, expires_at, user_limit,
                          revenue_limit, status, notified
                   FROM admin_access WHERE user_id=?""", (user_id,))
    row=cur.fetchone()
    if not row:
        conn.close()
        return None

    # IMPORTANT: New-admin PLAN STATUS must use only payments handled by
    # this admin AFTER the current plan was activated.  The old implementation
    # used global bot totals, so a newly purchased plan incorrectly started
    # with the Permanent Admin's historical revenue.
    activated_at = row[2]
    if activated_at:
        cur.execute("""SELECT COUNT(DISTINCT user_id), COALESCE(SUM(amount), 0)
                       FROM payment_records
                       WHERE approved_by=? AND payment_type='user'
                         AND status='approved' AND approved_at >= ?""",
                    (user_id, activated_at))
        scoped_users, scoped_revenue = cur.fetchone()
    else:
        scoped_users, scoped_revenue = 0, 0
    conn.close()
    return {
        "user_id": row[0], "plan": row[1], "activated_at": row[2],
        "expires_at": row[3], "user_limit": None if row[4] < 0 else row[4],
        "revenue_limit": None if row[5] < 0 else row[5],
        "status": row[6], "notified": row[7] or "", "unrestricted": False,
        "users": int(scoped_users or 0), "revenue": int(scoped_revenue or 0),
    }

def _is_expired_or_limited(access: dict):
    if not access or access.get("unrestricted"):
        return False, ""
    import datetime
    now=datetime.datetime.utcnow()
    if access.get("expires_at"):
        try:
            if now >= datetime.datetime.strptime(access["expires_at"], "%Y-%m-%d %H:%M:%S"):
                return True, "TIME"
        except ValueError:
            pass
    if access.get("user_limit") is not None and access["users"] > access["user_limit"]:
        return True, "USERS"
    if access.get("revenue_limit") is not None and access["revenue"] > access["revenue_limit"]:
        return True, "REVENUE"
    if access.get("status") != "ACTIVE":
        return True, "EXPIRED"
    return False, ""

def mark_access_expired(user_id: int, reason: str):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("UPDATE admin_access SET status='EXPIRED' WHERE user_id=?", (int(user_id),))
    cur.execute("SELECT 1 FROM admin_access_events WHERE user_id=? AND event_type=?", (int(user_id), "LIMIT_"+reason))
    already=cur.fetchone()
    if not already:
        cur.execute("INSERT INTO admin_access_events(user_id,event_type) VALUES(?,?)", (int(user_id), "LIMIT_"+reason))
    conn.commit(); conn.close()
    return already is None

def create_premium_key(plan: str, created_by: int):
    import secrets, hashlib
    plan=str(plan).upper()
    if plan not in ("PREMIUM_LITE","PREMIUM_XD","PREMIUM_PRO"):
        raise ValueError("Invalid premium plan")
    raw="PX-"+plan.replace("PREMIUM_","")+"-"+secrets.token_urlsafe(18).upper().replace("-","_")
    key_hash=hashlib.sha256(raw.encode()).hexdigest()
    hint=raw[-6:]
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""INSERT INTO premium_keys(key_hash,key_hint,plan,created_by) VALUES(?,?,?,?)""", (key_hash,hint,plan,int(created_by)))
    conn.commit(); conn.close()
    return raw

def create_custom_premium_key(user_limit: int, revenue_limit: int, days: int, created_by: int):
    import secrets, hashlib
    user_limit=int(user_limit); revenue_limit=int(revenue_limit); days=int(days)
    if user_limit <= 0 or revenue_limit < 0 or days <= 0:
        raise ValueError("USER, REVENUE and TIME must be positive values")
    raw="PX-CUSTOM-"+secrets.token_urlsafe(20).upper().replace("-","_")
    key_hash=hashlib.sha256(raw.encode()).hexdigest()
    hint=raw[-6:]
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""INSERT INTO premium_keys
        (key_hash,key_hint,plan,created_by,custom_user_limit,custom_revenue_limit,custom_days)
        VALUES(?,?,?,?,?,?,?)""", (key_hash,hint,"CUSTOM",int(created_by),user_limit,revenue_limit,days))
    conn.commit(); conn.close()
    return raw

def redeem_premium_key(user_id: int, raw_key: str):
    import hashlib
    raw_key=str(raw_key).strip()
    if not raw_key:
        return False, "INVALID", None
    key_hash=hashlib.sha256(raw_key.encode()).hexdigest()
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""SELECT key_id, plan, status, custom_user_limit, custom_revenue_limit, custom_days
                   FROM premium_keys WHERE key_hash=?""", (key_hash,))
    row=cur.fetchone()
    if not row:
        conn.close(); return False, "INVALID", None
    if row[2] != "UNUSED":
        conn.close(); return False, "USED", row[1]
    user_id=int(user_id)
    if user_id == config_permanent_admin():
        conn.close(); return False, "PERMANENT", row[1]
    cur.execute("SELECT 1 FROM admin_users WHERE user_id=?", (user_id,))
    if not cur.fetchone():
        cur.execute("INSERT INTO admin_users(user_id) VALUES(?)", (user_id,))
    if row[1] == "CUSTOM":
        import datetime
        now=datetime.datetime.utcnow()
        expires=(now + datetime.timedelta(days=int(row[5]))).strftime("%Y-%m-%d %H:%M:%S")
        cur.execute("""INSERT INTO admin_access
            (user_id,plan,activated_at,expires_at,user_limit,revenue_limit,status,notified)
            VALUES(?,?,?,?,?,?, 'ACTIVE','')
            ON CONFLICT(user_id) DO UPDATE SET plan=excluded.plan,activated_at=excluded.activated_at,
            expires_at=excluded.expires_at,user_limit=excluded.user_limit,revenue_limit=excluded.revenue_limit,
            status='ACTIVE',notified=''""", (user_id,"CUSTOM",now.strftime("%Y-%m-%d %H:%M:%S"),expires,int(row[3]),int(row[4])))
    else:
        _set_access_for_conn(cur, user_id, row[1])
    cur.execute("""UPDATE premium_keys SET status='USED', used_by=?, used_at=CURRENT_TIMESTAMP
                   WHERE key_id=? AND status='UNUSED'""", (user_id,row[0]))
    if cur.rowcount != 1:
        conn.rollback(); conn.close(); return False, "USED", row[1]
    conn.commit(); conn.close()
    return True, "OK", row[1]

def get_custom_premium_details(raw_key: str):
    import hashlib
    key_hash=hashlib.sha256(str(raw_key).strip().encode()).hexdigest()
    conn=get_connection(); cur=conn.cursor()
    cur.execute("SELECT custom_user_limit,custom_revenue_limit,custom_days FROM premium_keys WHERE key_hash=?", (key_hash,))
    row=cur.fetchone(); conn.close()
    return row

def set_admin_log_channel(user_id: int, channel: str):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""INSERT INTO admin_log_channels(user_id,channel,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)
                   ON CONFLICT(user_id) DO UPDATE SET channel=excluded.channel,updated_at=CURRENT_TIMESTAMP""", (int(user_id),str(channel)))
    conn.commit(); conn.close()

def get_admin_log_channel(user_id: int):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("SELECT channel FROM admin_log_channels WHERE user_id=?", (int(user_id),))
    row=cur.fetchone(); conn.close()
    return row[0] if row else None

def set_admin_upi(user_id: int, upi_id: str):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("INSERT INTO admin_upis(user_id,upi_id,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET upi_id=excluded.upi_id,updated_at=CURRENT_TIMESTAMP", (int(user_id), str(upi_id).strip()))
    conn.commit(); conn.close()

def get_admin_upi(user_id: int):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("SELECT upi_id FROM admin_upis WHERE user_id=?", (int(user_id),))
    row=cur.fetchone(); conn.close()
    return row[0] if row else ""

def clear_active_admin_upi(user_id: int):
    # Keep the saved UPI for the owner so it can be restored after a new plan is activated.
    conn=get_connection(); cur=conn.cursor()
    cur.execute("UPDATE settings SET value=? WHERE key='upi_id'", (get_setting('permanent_upi_id'),))
    conn.commit(); conn.close()

def reset_admin_log_channel(user_id: int):
    conn=get_connection(); cur=conn.cursor(); cur.execute("DELETE FROM admin_log_channels WHERE user_id=?", (int(user_id),)); conn.commit(); conn.close()

def get_premium_key_record(key_id: int):
    conn=get_connection(); cur=conn.cursor()
    cur.execute("SELECT plan,custom_user_limit,custom_revenue_limit,custom_days FROM premium_keys WHERE key_id=?", (int(key_id),))
    row=cur.fetchone(); conn.close(); return row

def get_premium_keys(plan=None, limit=20):
    conn=get_connection(); cur=conn.cursor()
    if plan:
        cur.execute("""SELECT key_hint, plan, status, created_at, used_by, used_at
                       FROM premium_keys WHERE plan=? ORDER BY key_id DESC LIMIT ?""",
                    (str(plan).upper(), int(limit)))
    else:
        cur.execute("""SELECT key_hint, plan, status, created_at, used_by, used_at
                       FROM premium_keys ORDER BY key_id DESC LIMIT ?""", (int(limit),))
    rows=cur.fetchall(); conn.close(); return rows

def get_admin_access_snapshot():
    conn=get_connection(); cur=conn.cursor()
    cur.execute("""SELECT a.user_id,a.plan,a.status,a.activated_at,a.expires_at,
                          a.user_limit,a.revenue_limit,a.notified
                   FROM admin_access a ORDER BY a.user_id""")
    rows=cur.fetchall(); conn.close()
    return rows

def reset_non_database_state():
    """Reset bot configuration/new admins while preserving the database data."""
    conn = get_connection(); cursor = conn.cursor()
    cursor.execute("DELETE FROM settings")
    cursor.execute("DELETE FROM buttons")
    cursor.execute("DELETE FROM menu_buttons")
    cursor.execute("DELETE FROM admin_users")
    cursor.execute("DELETE FROM admin_access")
    cursor.execute("DELETE FROM premium_keys")
    cursor.execute("DELETE FROM admin_access_events")
    cursor.execute("INSERT INTO settings (key,value) VALUES ('upi_id','your_upi@ybl')")
    cursor.execute("INSERT INTO settings (key,value) VALUES ('demo_link','https://t.me/your_demo_channel')")
    cursor.execute("INSERT INTO settings (key,value) VALUES ('contact_link','https://t.me/your_contact_link')")
    cursor.execute("INSERT INTO settings (key,value) VALUES ('permanent_upi_id','')")
    for bid, label, price in ((1,'PREMIUM LITE',199),(2,'PREMIUM XD',299),(3,'PREMIUM PRO',399)):
        cursor.execute("INSERT INTO buttons (btn_id,text,price) VALUES (?,?,?)", (bid,label,price))
    cursor.execute("INSERT INTO menu_buttons (btn_id,text,link) VALUES (1,'PREMIUM','')")
    cursor.execute("INSERT INTO menu_buttons (btn_id,text,link) VALUES (2,'DEMO','')")
    cursor.execute("INSERT INTO menu_buttons (btn_id,text,link) VALUES (3,'CONTACT','')")
    conn.commit(); conn.close()

def get_dashboard_snapshot() -> dict:
    return {
        "total_users": get_total_users_count(),
        "live_users": get_live_users_count(),
        "total_payments": get_stat("payments"),
        "total_amount": get_stat("total_amount"),
        "new_admin_count": len(get_new_admins()),
    }
